export const REFERENCES = [
  ['Sidnei', 'https://terceirotempo.uol.com.br/imagens/44/88/w500_h140_qfl_fto_14488.webp', 'https://pt.wikipedia.org/wiki/Sidney_Tobias'],
  ['Macedo', 'https://terceirotempo.uol.com.br/imagens/94/89/w615_h470_arq_179489.webp', 'https://pt.wikipedia.org/wiki/Macedo_(futebolista)'],
  ['Talles Costa', 'https://noticiasdosaopaulo.com.br/wp-content/uploads/2024/01/3348_crop_galeria.jpg', 'https://www.transfermarkt.pt/talles-costa/profil/spieler/627222'],
  ['Silas', 'https://terceirotempo.uol.com.br/imagens/37/23/w500_h140_qfl_fto_13723.webp', 'https://pt.wikipedia.org/wiki/Paulo_Silas'],
  ['Benitez', 'https://www.arqtricolor.com/wp-content/uploads/2021/05/benitez-sao-paulo-08.jpg.webp', 'https://pt.wikipedia.org/wiki/Mart%C3%ADn_Ben%C3%ADtez'],
  ['Cate', 'https://s.glbimg.com/jo/g1/f/original/2011/12/27/cate300x200.jpg', 'https://pt.wikipedia.org/wiki/Cat%C3%AA'],
  ['Piau', 'https://terceirotempo.uol.com.br/imagens/89/37/w500_h360_arq_208937.webp', 'https://pt.wikipedia.org/wiki/Eronides_de_Sousa'],
  ['Vaz', 'http://www.zerozero.pt/images/dsgn/No_Photo_00001.png', 'https://www.ogol.com.br/jogador/vaz/777464?epoca_id=70'],
  ['Capitao', 'https://ge.globo.com/Esportes/foto/0,,15649073-EX,00.jpg', 'https://pt.wikipedia.org/wiki/Capit%C3%A3o_(futebolista)'],
  ['Muricy', 'https://cdn.acritica.net/img/pc/920/600/dn_arquivo/2024/02/50d8e9a973d149b7bab558d795890a6f.jpg', 'https://pt.wikipedia.org/wiki/Muricy_Ramalho'],
  ['Alfredo Ramos', 'https://s2.glbimg.com/SHqgfWcckFvBZ3-tQcYtmBQbWJL0QzS350Wnd6NP_o9iDsu-kYcWfE1joDeEMH_u/s.glbimg.com/es/ge/f/original/2012/07/31/alfredoamos-saopaulo-div.jpg', 'https://pt.wikipedia.org/wiki/Alfredo_Ramos'],
  ['Baia', 'http://www.zerozero.pt/images/dsgn/No_Photo_00001.png', 'https://www.ogol.com.br/jogador/baia/778039?idpais=11%7C1'],
  ['Vagner', 'https://www.arqtricolor.com/wp-content/uploads/2020/06/vagner.jpg', 'https://pt.wikipedia.org/wiki/V%C3%A1gner_Rog%C3%A9rio_Nunes'],
  ['Paulão Desmaio', 'https://pbs.twimg.com/profile_images/1006729949657616384/McXR6nBE_400x400.jpg', 'https://www.zerozero.pt/jogador/paulao/162486'],
  ['Joilson', 'https://www.lance.com.br/galerias/wp-content/uploads/2020/05/Joilson-S%C3%A3o-Paulo-Divulga%C3%A7%C3%A3o.jpeg', 'https://pt.wikipedia.org/wiki/Jo%C3%ADlson'],
  ['Julio Baptista', 'https://f.i.uol.com.br/folha/esporte/images/09078272.jpg', 'https://pt.wikipedia.org/wiki/J%C3%BAlio_Baptista'],
  ['Gérsio Passadore', 'https://tardesdepacaembu.files.wordpress.com/2023/11/imagem7.png', 'https://pt.wikipedia.org/wiki/G%C3%A9rsio_Passadore'],
  ['Antony', 'https://d3nfwcxd527z59.cloudfront.net/content/uploads/2022/08/31122104/Antony-Sao-Paulo-Copinha.jpg', 'https://pt.wikipedia.org/wiki/Antony_Matheus_dos_Santos'],
  ['Annibal', 'https://www.zerozero.pt/img/jogadores/60/775460_annibal.png', 'https://www.ogol.com.br/jogador/annibal/775460'],
  ['Pablo Maia', 'https://a.espncdn.com/combiner/i?img=%2Fphoto%2F2022%2F1117%2Fr1092507_1296x729_16%2D9.jpg', 'https://pt.wikipedia.org/wiki/Pablo_Maia'],
  ['Nelsinho', '', ''],
  ['Samuel', '', ''],
  ['Rafael', '', ''],
  ['Picasso', '', ''],
  ['Vitor Bueno', '', ''],
  ['Iracino', '', ''],
  ['Beraldo', '', ''],
  ['Rai', '', ''],
  ['Bellini', '', ''],
  ['Gilmar', '', ''],
  ['Suly', '', ''],
  ['Aldo', '', ''],
  ['Souza', '', ''],
  ['Edmilson', '', ''],
  ['Dario Pereyra', '', ''],
  ['Antonio Carlos', '', ''],
  ['Bibe', '', ''],
  ['Turcao', '', ''],
  ['Kaka', '', ''],
  ['Douglas', '', ''],
  ['Aloisio', '', ''],
  ['Rhodolfo', '', ''],
  ['Rui', '', ''],
  ['Leopoldo', '', ''],
  ['Carlos Miguel', '', ''],
  ['Pedro Rocha', '', ''],
  ['Lanzoninho', '', ''],
  ['Fonseca', '', ''],
  ['Dodo', '', ''],
  ['King', '', ''],
  ['Volpi', '', ''],
  ['Luciano', '', ''],
  ['Jadson', '', ''],
  ['Felipe Alves', '', ''],
  ['Edson Cegonha', '', ''],
  ['Ademilson', '', ''],
  ['Fernandinho', '', ''],
  ['Ary', '', ''],
  ['Renato', '', ''],
  ['Nene', '', ''],
  ['Sastre', '', ''],
  ['Evair', '', ''],
  ['Almir', '', ''],
  ['Liziero', '', ''],
  ['Parana', '', ''],
  ['Luan', '', ''],
  ['Borges', '', ''],
  ['Lucas', '', ''],
  ['Jancarlos', '', ''],
  ['Gijo', '', ''],
  ['Reinaldo', '', ''],
  ['Leo', '', ''],
  ['Cicero', '', ''],
  ['Richarlyson', '', ''],
  ['Forlan', '', ''],
  ['Adriano', '', ''],
  ['Ivan', '', ''],
  ['Josue', '', ''],
  ['Casemiro', '', ''],
  ['Paulo Cesar', '', ''],
  ['Chicao', '', ''],
  ['Mineiro', '', ''],
  ['Thiago Ribeiro', '', ''],
  ['Roberto Dias', '', ''],
  ['Marcio Santos', '', ''],
  ['Cicinho', '', ''],
  ['Tardelli', '', ''],
  ['Gassem', '', ''],
  ['Lio', '', ''],
  ['Saverio', '', ''],
  ['Ferreira', '', ''],
  ['James Rodriguez', '', ''],
  ['Andre Luiz', '', ''],
  ['Fabio Santos', '', ''],
  ['Paulo Nani', '', ''],
  ['Arboleda', '', ''],
  ['Ademir', '', ''],
  ['Ricardo Rocha', '', ''],
  ['Alex Silva', '', ''],
  ['Ilsinho', '', ''],
  ['Mena', '', ''],
  ['Juninho', '', ''],
  ['Nelson', '', ''],
  ['Baiano', '', ''],
  ['Galoppo', '', ''],
  ['Teodoro', '', ''],
  ['Gallo', '', ''],
  ['Everton', '', ''],
  ['Bordon', '', ''],
  ['Maurinho', '', ''],
  ['Danilo', '', ''],
  ['Alex', '', ''],
  ['Nem', '', ''],
  ['Adilson', '', ''],
  ['Canhoteiro', '', ''],
  ['Chulapa', '', ''],
  ['Rogerio Ceni', '', ''],
  ['Waldir Peres', '', ''],
  ['Diego Costa', '', ''],
  ['Moreira', '', ''],
  ['Jean', '', ''],
  ['David', '', ''],
  ['Miranda', '', ''],
  ['Leonidas', '', ''],
  ['Tim', '', ''],
  ['Denis', '', ''],
  ['Gilmar', '', ''],
  ['Palhinha', '', ''],
  ['Hudson', '', ''],
  ['Mirandinha', '', ''],
  ['Marcio Araujo', '', ''],
  ['Rato', '', ''],
  ['Alan Franco', '', ''],
  ['Thiago Mendes', '', ''],
  ['Lucio', '', ''],
  ['Viana', '', ''],
  ['Axel', '', ''],
  ['Dagoberto', '', ''],
  ['Pardal', '', ''],
  ['Michel Bastos', '', ''],
  ['Ademar', '', ''],
  ['Rodrigo Caio', '', ''],
  ['Leonardo', '', ''],
  ['Claudio', '', ''],
  ['Bauer', '', ''],
  ['Fiorotti', '', ''],
  ['Agenor', '', ''],
  ['Oscar', '', ''],
  ['Ronaldao', '', ''],
  ['Cafu', '', ''],
  ['Andre Dias', '', ''],
  ['Zarzur', '', ''],
  ['Pita', '', ''],
  ['Galeano', '', ''],
  ['Mauro', '', ''],
  ['Julio Santos', '', ''],
  ['Gabriel', '', ''],
  ['Ede', '', ''],
  ['Jucilei', '', ''],
  ['Jean', '', ''],
  ['Rafael Toloi', '', ''],
  ['Pintado', '', ''],
  ['Getulio', '', ''],
  ['Lenilson', '', ''],
  ['Edcarlos', '', ''],
  ['Matheus Reis', '', ''],
  ['Wilson', '', ''],
  ['Faustino', '', ''],
  ['Marcelinho PB', '', ''],
  ['Axel', '', ''],
  ['Teixeirinha', '', ''],
  ['Jurandir', '', ''],
  ['Paranhos', '', ''],
  ['Luiz Gustavo', '', ''],
  ['Carlinhos', '', ''],
  ['Bruno', '', ''],
  ['Netinho', '', ''],
  ['Rodrigo Souto', '', ''],
  ['Souza', '', ''],
  ['Igor Vinicius', '', ''],
  ['Cleber Santana', '', ''],
  ['Neca', '', ''],
  ['Ney Bala', '', ''],
  ['Fabiano', '', ''],
  ['Cortez', '', ''],
  ['Denilson', '', ''],
  ['Terto', '', ''],
  ['Fernandao', '', ''],
  ['Nei', '', ''],
  ['Renatinho', '', ''],
  ['André Silva', '', ''],
  ['Eder Luis', '', ''],
  ['Estevam', '', ''],
  ['Ponce de Leon', '', ''],
  ['Felipelli', '', ''],
  ['Pato', '', ''],
  ['Ze Roberto', '', ''],
  ['Alexandre', '', ''],
  ['Dinho', '', ''],
  ['Junior Cesar', '', ''],
  ['Edson Silva', '', ''],
  ['Rodrigo', '', ''],
  ['Ze Sergio', '', ''],
  ['Ronaldo Luis', '', ''],
  ['Flavio', '', ''],
  ['Rodrigo Fabri', '', ''],
  ['Carlos Alberto', '', ''],
  ['Rogerio Pinheiro', '', ''],
  ['Edu Bala', '', ''],
  ['Igor Gomes', '', ''],
  ['Alan', '', ''],
  ['Shaylon', '', ''],
  ['Fabao', '', ''],
  ['Jorge Wagner', '', ''],
  ['Renganeschi', '', ''],
  ['Jose Poy', '', ''],
  ['Marlos', '', ''],
  ['Ganso', '', ''],
  ['Tecao', '', ''],
  ['Antenor', '', ''],
  ['Gino Orlando', '', ''],
  ['Muller', '', ''],
  ['Gustavo Nery', '', ''],
  ['Pablo', '', ''],
  ['Mug', '', ''],
  ['Ze Carlos', '', ''],
  ['Bobadilla', '', ''],
  ['Edivaldo', '', ''],
  ['Elivelton', '', ''],
  ['Noronha', '', ''],
  ['Gabriel Sara', '', ''],
  ['Serginho', '', ''],
  ['Ricardo Oliveira', '', ''],
  ['Renato', '', ''],
  ['Hugo', '', ''],
  ['Pianelli', '', ''],
  ['Sorriso', '', ''],
  ['Clelio', '', ''],
  ['T Guerreiro', '', ''],
  ['Franca', '', ''],
  ['Luizinho', '', ''],
  ['Tom', '', ''],
  ['Baba', '', ''],
  ['De Sordi', '', ''],
  ['Hernanes', '', ''],
  ['Piolim', '', ''],
  ['Mario', '', ''],
  ['Dino Sani', '', ''],
  ['Alisson', '', ''],
  ['Araken Patusca', '', ''],
  ['Lourival', '', ''],
  ['Ricardinho', '', ''],
  ['Heriberto', '', ''],
  ['William Jose', '', ''],
  ['Remo', '', ''],
  ['Paulo Miranda', '', ''],
  ['Deleu', '', ''],
  ['Toinho', '', ''],
  ['Aristizabal', '', ''],
  ['Ruy', '', ''],
  ['Calleri', '', ''],
  ['Luis Fabiano', '', ''],
  ['Armandinho', '', ''],
  ['Nei', '', ''],
  ['Joe', '', ''],
  ['Mario Tilico', '', ''],
  ['Victor', '', ''],
  ['Baba', '', ''],
  ['Bene', '', ''],
  ['Auro', '', ''],
  ['Roberto', '', ''],
  ['Nestor', '', ''],
  ['Maicon', '', ''],
  ['Zetti', '', ''],
  ['Alex Dias', '', ''],
  ['Wellington', '', ''],
  ['Bernardo', '', ''],
  ['Orozimbo', '', ''],
  ['Lyanco', '', ''],
  ['Lugano', '', ''],
  ['Careca', '', ''],
  ['Jandrei', '', ''],
  ['Rafinha', '', ''],
  ['Junior', '', ''],
  ['Ale', '', ''],
  ['Bezerra', '', ''],
  ['Osvaldo', '', ''],
  ['Euller', '', ''],
  ['Riberto', '', ''],
  ['Bosco', '', ''],
  ['Andre Lima', '', ''],
  ['Ruy', '', ''],
  ['Belletti', '', ''],
  ['Ferraresi', '', ''],
  ['Ramalho', '', ''],
  ['Valber', '', ''],
  ['Simplicio', '', ''],
  ['Fabio Aurelio', '', ''],
  ['Bruno Alves', '', ''],
  ['Prado', '', ''],
  ['Leo', '', ''],
  ['Friedenreich', '', ''],
  ['Xandao', '', ''],
  ['Leandro', '', ''],
  ['Igor Gomes', '', ''],
  ['Erick', '', ''],
  ['Sergio', '', ''],
  ['Edu', '', ''],
  ['Denilson', '', ''],
  ['Vitor', '', ''],
  ['Zoe', '', ''],
  ['Ze Teodoro', '', ''],
  ['Amaury', '', ''],
  ['Arlindo', '', ''],
  ['Tenente', '', ''],
]